image: maven:3-jdk-8

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=.m2/repository --batch-mode"

stages:
  - compile
  - analysis
  - test
  - package
  - deploy

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass

compile:
  stage: compile
  only:
    - dev
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS clean compile'

pmd:
  stage: analysis
  only:
    - dev
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS clean pmd:check'
  artifacts:
    paths:
      - target/site/pmd.html
    when: on_failure

checkstyle:
  stage: analysis
  only:
    - dev
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS clean checkstyle:check'

findbugs:
  stage: analysis
  only:
    - dev
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS clean compile findbugs:check'

test:
  stage: test
  only:
    - dev
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS clean test'

package:
  stage: package
  only:
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS clean package'
  artifacts:
    paths:
      - target/*.war

deploy:
  stage: deploy
  environment: Staging
  only:
    - master
  script:
    - cd target/
    - ls
    - sshpass -V
    - export SSHPASS=$CI_PASSWORD
    - sshpass -e scp -o stricthostkeychecking=no -r *.war $CI_USERNAME@$CI_IP:$BE_HOME